import zira from "../assets/ccondiments/z.png";
import tz from "../assets/ccondiments/t.png";
import shz from "../assets/ccondiments/sh.png";
import qq from "../assets/ccondiments/qq.png";
import lz from "../assets/ccondiments/l.png";
import d from "../assets/ccondiments/druja.png";
import aralashma from "../assets/ccondiments/aralashma.png";

export const CONDIMENTS_STATIC = [
  {
    id: 0,
    name: "Zira",
    price: "3 500",
    image: zira,
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Ziravor",
    price: "3 500",
    image: tz,
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Druja",
    price: "6 000",
    image: d,
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Ziravor",
    price: "3 500",
    image: shz,
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Qalampir",
    price: "3 500",
    image: qq,
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Ziravor",
    price: "3 500",
    image: lz,
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Ziravor",
    price: "3 500",
    image: aralashma,
    amount: "1 Dona",
  },
];
