export const DRINKS_STATIC = [
  {
    id: 0,
    name: "Dena",
    price: "3 500",
    image: "https://studiomart.ru/files/works/3154.jpg",
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Bliss",
    price: "4 000",
    image:
      "https://catalog.korzinka.uz/storage/catalog-products/2024/2/small_65dd703630aca.png",
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Dimes",
    price: "3 000",
    image:
      "https://down-my.img.susercontent.com/file/my-11134207-7r990-lqqfuhx9ymdx2d",
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Любимый",
    price: "3 500",
    image:
      "https://marketyan.am/media/image/d4/f9/db/46015120067248QoxJjzlXla1c_600x600.jpg",
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Gorilla",
    price: "3 000",
    image: "https://gorillaenergy.by/img/socials/5.jpg",
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Blue Agave",
    price: "5 000",
    image:
      "https://gdimg.gmarket.co.kr/goods_image2/shop_moreimg/476/980/476980903/476980903_01.jpg?ver=1536738286",
    amount: "1 Dona",
  },
  {
    id: 1,
    name: "Moxito",
    price: "3 000",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGTXWl186dvtY9tfX_sPCv6xGofJ_waG_9GtN4cQNxbmhhGrPZfU-vtGeOAITOt7vjzgU&usqp=CAU",
    amount: "1 Dona",
  },
];
